apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk-kart-deployment
  labels:
    app: sk-kart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk-kart
  template:
    metadata:
      labels:
        app: sk-kart
    spec:
      containers:
      - name: sk-kart
        image: sk/kart:1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sk-kart-service
  labels:
    app: sk-kart
spec:
  selector:
    app: sk-kart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
